backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Post',
          name: 'featuredpost',
          widget: 'boolean',
          required: false,
        }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          field: { label: Tag, name: tag, widget: string },
        }
      - label: 'Country'
        name: 'country'
        widget: 'relation'
        collection: 'country'
        searchFields: ['title']
        valueField: 'title'
        required: false
        displayFields: ['title']

      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'category'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']
        multiple: true

      - label: 'Author'
        name: 'author'
        widget: 'relation'
        collection: 'authors'
        searchFields: ['name']
        valueField: 'title'
        displayFields: ['title']

      - label: 'Guest Author'
        name: 'guest-author'
        widget: 'relation'
        collection: 'guest-authors'
        searchFields: ['name', 'instagram']
        valueField: 'title'
        required: false
        displayFields: ['title']

  - name: 'category'
    label: 'Category'
    folder: 'src/pages/categories'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Site Setting',
          name: 'siteSettings',
          widget: 'hidden',
          default: 'blog-nav',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'country'
    label: 'Country'
    folder: 'src/pages/destinations'
    create: true
    slug: 'destinations/{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-country',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'tags'
    label: 'Tag'
    folder: 'src/pages/tags'
    create: true
    slug: '/tags/{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }

  - name: 'authors'
    label: 'Authors'
    folder: 'src/pages/authors'
    create: true
    slug: 'author/{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-author',
        }
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Bio (In Markdown)', name: 'bio', widget: 'markdown' }
      - { label: 'Photo', name: 'photo', widget: image }
      - { label: 'Website', name: 'website', widget: 'string', required: false }
      - {
          label: 'Instagram',
          name: 'instagram',
          widget: 'string',
          required: false,
        }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - {
          label: 'Pinterest',
          name: 'pinterest',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Facebook',
          name: 'facebook',
          widget: 'string',
          required: false,
        }

  - name: 'guest-authors'
    label: 'Guest Authors'
    folder: 'src/pages/guest-authors'
    create: true
    slug: 'guest-author/{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-author',
        }
      - { label: 'Name', name: 'title', widget: 'string' }
      - { label: 'Bio (In Markdown)', name: 'bio', widget: 'markdown' }
      - { label: 'Photo', name: 'photo', widget: image, required: false }
      - { label: 'Website', name: 'website', widget: 'string', required: false }
      - {
          label: 'Instagram',
          name: 'instagram',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Facebook',
          name: 'facebook',
          widget: 'string',
          required: false,
        }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Landing Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Subheading, name: subheading, widget: string }
          - {
              label: Mainpitch,
              name: mainpitch,
              widget: object,
              fields:
                [
                  { label: Title, name: title, widget: string },
                  { label: Description, name: description, widget: text },
                ],
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
      - file: 'src/pages/about/index.md'
        label: 'About'
        name: 'about'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'about-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - file: 'src/pages/products/index.md'
        label: 'Products Page'
        name: 'products'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'product-page',
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          - {
              label: Intro,
              name: intro,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Blurbs,
                    name: blurbs,
                    widget: list,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Text, name: text, widget: text },
                      ],
                  },
                ],
            }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
