backend:
  name: git-gateway
  branch: develop

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: blog/{{slug}}
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Post',
          name: 'featuredpost',
          widget: 'boolean',
          required: false,
        }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - {
          label: 'Featured Image Description (add credits from unsplash or other websites in the figcaption)',
          name: 'imagealt',
          widget: markdown,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          field: { label: Tag, name: tag, widget: string },
        }
      - label: 'Country'
        name: 'country'
        widget: 'relation'
        collection: 'country'
        searchFields: ['title']
        valueField: 'title'
        required: false
        displayFields: ['title']
        multiple: true

      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'category'
        searchFields: ['title']
        valueField: 'title'
        displayFields: ['title']
        multiple: true

      - label: 'Author'
        name: 'author'
        widget: 'relation'
        collection: 'authors'
        searchFields: ['name']
        valueField: 'name'
        displayFields: ['name']

  - name: 'category'
    label: 'Category'
    folder: 'src/pages/categories'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Site Setting',
          name: 'siteSettings',
          widget: 'hidden',
          default: 'blog-nav',
        }
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'categories',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - {
          label: 'Featured Image',
          name: 'photo',
          widget: image,
          required: false,
        }

  - name: 'country'
    label: 'Country'
    folder: 'src/pages/countries'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-country',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Photo', name: 'photo', widget: image }

  - name: 'authors'
    label: 'Authors'
    folder: 'src/pages/authors'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'blog-author',
        }
      - {
          label: 'Role',
          name: 'role',
          widget: 'select',
          options: ['author', 'guest-author'],
        }
      - { label: 'Name', name: 'title', widget: 'string' }

      - { label: 'Bio (In Markdown)', name: 'bio', widget: 'markdown' }
      - { label: 'Photo', name: 'photo', widget: image }
      - { label: 'Website', name: 'website', widget: 'string', required: false }
      - {
          label: 'Instagram',
          name: 'instagram',
          widget: 'string',
          required: false,
        }
      - { label: 'Twitter', name: 'twitter', widget: 'string', required: false }
      - {
          label: 'Pinterest',
          name: 'pinterest',
          widget: 'string',
          required: false,
        }
      - {
          label: 'Facebook',
          name: 'facebook',
          widget: 'string',
          required: false,
        }

  - name: 'pages'
    label: 'Pages'
    folder: 'src/pages/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Page content', name: 'body', widget: 'markdown' }
      - { label: 'Photo', name: 'photo', widget: image, required: false }
